### PR TITLE
Added spanish translation

### PR DESCRIPTION
**Pull request by borekon**
Added spanish translation. May be improved

### CODE REVIEW

**Comment by fredl99** [comment]
Thank you very much, @borekon !
You might want to put your name as "last translator" into your files, before I merge them, don't you?
Regards,
Fredl.

**Comment by borekon** [comment]
Hi, 
It would be great. 
It is my very first time using github 😅
How to do it? 
El 16 nov. 2016 8:41 p. m., Fredl notifications@github.com escribió:Thank you very much, @borekon !
You might want to put your name as "last translator" into your files, before I merge them, don't you?
Regards,
Fredl.

**Comment by fredl99** [comment]
Which software did you use for the translation and creation of the *.mo file? This software usually has an option to set your name.

If in doubt you could also edit your *.po file with a texteditor and then recompile the *.mo file. It depends on your toolchain.

**Comment by borekon** [comment]
I read your github Readme and used poedit. 
I will take another look and pull again the request. 
El 17 nov. 2016 12:15 a. m., Fredl notifications@github.com escribió:Which software did you use for the translation and creation of the *.mo file? This software usually has an option to set your name.

If in doubt you could also edit your *.po file with a texteditor and then recompile the *.mo file. It depends on your toolchain.

**Comment by fredl99** [comment]
Well done, @borekon :+1: 
Your translation looks great (for me...)
Thanks for sharing!

**Pull request merged**
